
LINES_PADDING = 500
ON_LINE_DISTANCE = 300
LIFE_THRESHOLD_FOR_SAVING = 50
FARM_POINT_OFFSET = 50  # must be less than ON_LINE_DISTANCE
LIFE_REGEN_OFFSET = 400
TARGET_DISTANCE_TO_STAY = 50
VANGUARD_ALLY_RADIUS = 400

STRAFE_OBJECT_MAX_DISTANCE = 20
NEAREST_RADIUS = 600  # equals to wizard vision range
MATRIX_CELL_SIZE = 40
MATRIX_CELL_AMOUNT = int(NEAREST_RADIUS * 2 / MATRIX_CELL_SIZE)

ALLY_TOWER_FORCE = 50
ALLY_TOWER_RADIUS_DELTA = 100
ENEMY_TOWER_FORCE = -200
TREE_FORCE = -150
TREE_RADIUS_DELTA = 100
OBJ_RADIUS_DELTA = 25
